### ISSUE TITLE
navis doesn't work with rpy2

### ISSUE THREAD

**Issue by SridharJagannathan** [schlegelp/navis#3]
The `navis` (and I think `pymaid`) as well doesn't work with the latest rpy2 module (3.3.2)
Steps are as follows:
1) Install rpy2 like `pip install rpy2`
2) Peform setup like 
```
import navis
navis.set_pbars(hide=True, jupyter=False)
from navis.interfaces import r
import matplotlib.pyplot as plt
from rpy2.robjects.packages import importr
import rpy2.robjects as robjects

```

3) Import `nat` and try to convert a r object to navis neuron format like below:
```
nat = importr('nat')
kcs20 = robjects.r('kcs20')
kcs20_py = r.dotprops2py(kcs20)

```

This gives following error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-9-338476923f8b> in <module>
----> 1 kcs20_py = r.dotprops2py(kcs20)

~/anaconda3/lib/python3.7/site-packages/navis/interfaces/r.py in dotprops2py(dp, subset)
    453     # This only works if inputs is a neuronlist of dotprops
    454     if 'neuronlist' in cl(dp):
--> 455         df = data2py(dp.slots['df'])
    456         df.reset_index(inplace=True, drop=True)
    457     else:

~/anaconda3/lib/python3.7/site-packages/navis/interfaces/r.py in data2py(data, **kwargs)
    225             return {n: float(data[i]) for i, n in enumerate(names(data))}
    226     elif cl(data)[0] == 'data.frame':
--> 227         return pandas2ri.ri2py(data)
    228     elif cl(data)[0] == 'matrix':
    229         mat = np.array(data)

AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'ri2py'

```

**Comment by schlegelp** [comment]
(Hopefully) Fixed with 667be95445d34c118a4e9274ba192bb55ec49300

Your example works on my system with R `3.6.3` and rpy `3.3.2`. I did bump the version to `0.1.15` but have not yet uploaded to PyPI. To test the fix update from Github:
```bash
pip3 install git+git://github.com/schlegelp/navis@master
```

**Comment by schlegelp** [comment]
I'm assuming this is fixed. Closing but feel free to reopen if issue persists.
